apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stats
  template:
    metadata:
      labels:
        app: stats
    spec:
      containers:
      - name: stats-container
        image: stats-service:v1
        ports:
        - containerPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: stats-service
spec:
  selector:
    app: stats
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8002
