apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: news
  template:
    metadata:
      labels:
        app: news
    spec:
      containers:
      - name: news-container
        image: news-service:v1
        ports:
        - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: news-service
spec:
  selector:
    app: news
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
